mode: increment
blade-directive: version
current:
  label: null
  major: 0
  minor: 4
  patch: 0
  prerelease: alpha
  format: '{$major}.{$minor}.{$patch}-{$prerelease}'
  buildmetadata: null
  commit: 26255a
  timestamp:
    year: 2022
    month: 12
    day: 13
    hour: 13
    minute: 43
    second: 43
    timezone: UTC
commit:
  mode: absorb
  length: 6
  increment-by: 1
git:
  from: local
  commit:
    local: 'git rev-parse --verify HEAD'
    remote: 'git ls-remote {$repository}'
  branch: refs/heads/master
  repository: ''
  version:
    local: 'git describe'
    remote: 'git ls-remote {$repository} | grep tags/ | grep -v {} | cut -d / -f 3 | sort --version-sort | tail -1'
    matcher: '/^(?P<label>[v|V]*[er]*[sion]*)[\.|\s]*(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/'
  timestamp:
    local: 'git show -s --format=%ci'
    remote: 'git show -s --format=%ci origin/master'
format:
  regex:
    optional_bracket: '\[(?P<prefix>.*?)(?P<spaces>\s*)(?P<delimiter>\?\=)(?P<optional>.*?)\]'
  label: '{$label}'
  major: '{$major}'
  minor: '{$minor}'
  patch: '{$patch}'
  prerelease: '{$prerelease}'
  buildmetadata: '{$buildmetadata}'
  commit: '{$commit}'
  version: '{$major}.{$minor}.{$patch} (commit {$commit})'
  version-only: '{$major}.{$minor}.{$patch}'
  full: '{$version-only}[.?={$prerelease}][+?={$buildmetadata}] (commit {$commit})'
  compact: '{$major}.{$minor}.{$patch}-{$commit}'
  changelog: '{$version-only}'
  changelog-rc: '{$version-only}[.?={$prerelease}][+?={$buildmetadata}]{$commit}'
  timestamp-year: '{$timestamp.year}'
  timestamp-month: '{$timestamp.month}'
  timestamp-day: '{$timestamp.day}'
  timestamp-hour: '{$timestamp.hour}'
  timestamp-minute: '{$timestamp.minute}'
  timestamp-second: '{$timestamp.second}'
  timestamp-timezone: '{$timestamp.timezone}'
  timestamp-datetime: '{$timestamp.year}-{$timestamp.month}-{$timestamp.day} {$timestamp.hour}:{$timestamp.minute}:{$timestamp.second}'
  timestamp-full: '{$timestamp.year}-{$timestamp.month}-{$timestamp.day} {$timestamp.hour}:{$timestamp.minute}:{$timestamp.second} {$timestamp.timezone}'
